# Generated by Django 5.0.6 on 2024-07-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
                ('image_Url', models.CharField(max_length=256)),
            ],
        ),
    ]
